-- One-shot sync of _prisma_migrations checksums to match current migration.sql files on disk.
-- Generated by scripts/sync-prisma-migration-checksums.mjs on 2026-05-14.
-- Safe to re-run: each statement is idempotent (sets the row to the exact same hash on the second run).
-- New migrations not yet applied (e.g. 20260514120000_bot_commands_settings) are intentionally omitted —
-- they will be INSERTed when `prisma migrate dev` runs next.
UPDATE "_prisma_migrations" SET checksum = '9ea754878f1c7b32fb3d106dc705e99cbd5a21af98b5ecace52428da3245530f' WHERE migration_name = '20260510141400_init';
UPDATE "_prisma_migrations" SET checksum = '0de6d5a87eb7adda29b93c9be85f54fd11a6f47436eec25df86bd174c05e97f3' WHERE migration_name = '20260510151656_perms_invites';
UPDATE "_prisma_migrations" SET checksum = '11bd85b4318a262038e9cba106a3f858ab38f03f0a5d8cf66806152c66e90de4' WHERE migration_name = '20260510164309_dashboard_layout';
UPDATE "_prisma_migrations" SET checksum = 'de36230cf258c45ab52e09a79dd30752cb53b9a8b5372ae35d07b44245358196' WHERE migration_name = '20260510200000_dock_locks_json';
UPDATE "_prisma_migrations" SET checksum = '90960458de0e37decbd9f55cd4a57f31db9643f755b1d5940831993c1766bd69' WHERE migration_name = '20260511185847_chat_message_archive';
UPDATE "_prisma_migrations" SET checksum = '5bfb059c27548f129a8e5acc31a7598901ca1e446e3534107e4278a07fb25a89' WHERE migration_name = '20260513120000_song_requests';
UPDATE "_prisma_migrations" SET checksum = '53bf95679b937e2a09d89b86f681b2c41923f890c4e2a387aed9289403df481b' WHERE migration_name = '20260513140000_song_request_reward_id';
UPDATE "_prisma_migrations" SET checksum = '08a08396d45af453d758f098fd8806402b6e3f1380b97d5099509ac57f0ddf5d' WHERE migration_name = '20260513150000_dashboard_layout_channel_prefs';
